# Generated by Django 5.2.8 on 2025-11-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
    ]
